require('packer-init')

require("core/settings")
require("core/colors")
require("core/keymaps")
require("core/statusline")

require("plugins/telescope")
require("plugins/whichkey")
require("plugins/lspconfig")
require("plugins/treesitter")
require("plugins/colorizer")
require("plugins/indent")
require("plugins/alpha")
require("plugins/cmp")
